### ISSUE TITLE
This will stop working in Home Assistant 2025.6,

### ISSUE THREAD

**Issue by dgillet1380** [goev/AlsavoProHomeAssistantIntegration#15]
This is the message I get in the startup log:

2025-06-13 10:10:56.945 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alsavopro' calls async_forward_entry_setup for integration, alsavopro with title: PAC piscine-xxx and entry_id: yyyyy, which is deprecated, await async_forward_entry_setups instead at custom_components/alsavopro/__init__.py, line 47: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please report it to the author of the 'alsavopro' custom integration

**Comment by lesotter** [comment]
2025-06-13 09:37:53.954 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry pool-824500030520 for alsavopro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alsavopro/__init__.py", line 48, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by lesotter** [comment]
for those wishing to fix this pending author fix, replace contents of "/config/custom_components/alsavopro/init.py" with the following code then restart home assistant. Enjoy!

"""Alsavo Pro pool heat pump integration."""
import logging
from datetime import timedelta

import async_timeout
from homeassistant.core import HomeAssistant
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
)

from homeassistant.const import (
    CONF_PASSWORD,
    CONF_IP_ADDRESS,
    CONF_PORT,
    CONF_NAME,
    Platform,
)

from .AlsavoPyCtrl import AlsavoPro
from .const import (
    DOMAIN,
    SERIAL_NO,
)

_LOGGER = logging.getLogger(__name__)

# Define platforms to be set up
PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.CLIMATE]


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Alsavo Pro component."""
    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up the Alsavo Pro heater from a config entry."""
    name = entry.data.get(CONF_NAME)
    serial_no = entry.data.get(SERIAL_NO)
    ip_address = entry.data.get(CONF_IP_ADDRESS)
    port_no = entry.data.get(CONF_PORT)
    password = entry.data.get(CONF_PASSWORD)

    data_handler = AlsavoPro(name, serial_no, ip_address, port_no, password)
    data_coordinator = AlsavoProDataCoordinator(hass, data_handler)

    await data_coordinator.async_config_entry_first_refresh()

    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = data_coordinator

    # This is the corrected line that replaces the old for loop.
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    # This is the corrected line for unloading.
    return await hass.config_entries.async_forward_entry_unloads(entry, PLATFORMS)


class AlsavoProDataCoordinator(DataUpdateCoordinator):
    """Class to manage fetching Alsavo Pro data from the device."""

    def __init__(self, hass: HomeAssistant, data_handler: AlsavoPro):
        """Initialize my coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="AlsavoPro",
            update_interval=timedelta(seconds=15),
        )
        self.data_handler = data_handler

    async def _async_update_data(self):
        """Fetch data from API endpoint."""
        _LOGGER.debug("Starting data update from Alsavo Pro device")
        try:
            async with async_timeout.timeout(10):
                await self.data_handler.update()
                _LOGGER.debug("Data update successful")
                return self.data_handler
        except Exception as ex:
            _LOGGER.error("Error communicating with Alsavo Pro device: %s", ex)
            raise

**Comment by lesotter** [comment]
Thanks to Google AI studio helping me with this!

**Comment by dgillet1380** [comment]
Thank you for this.
Alas, it doesn't work in y case:

Enregistreur: homeassistant.loader
Source: loader.py:1053
S'est produit pour la première fois: 10:57:46 (2 occurrences)
Dernier enregistrement: 10:57:46

Unexpected exception importing component custom_components.alsavopro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alsavopro/__init__.py", line 85
    `raise
    ^
SyntaxError: invalid syntax

**Comment by lesotter** [comment]
OK - there is a possibility that my entry here was wrongly formatted, or you and I are on different versions I guess
Try again (below) .  If not, paste your current init.py into Google AI and ask it to fix deprecated code...worked for me
```
"""Alsavo Pro pool heat pump integration."""
import logging
from datetime import timedelta

import async_timeout
from homeassistant.core import HomeAssistant
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
)

from homeassistant.const import (
    CONF_PASSWORD,
    CONF_IP_ADDRESS,
    CONF_PORT,
    CONF_NAME,
    Platform, # Import Platform enum for better type hinting and clarity
)

from .AlsavoPyCtrl import AlsavoPro
from .const import (
    DOMAIN,
    SERIAL_NO,
)

_LOGGER = logging.getLogger(__name__)

# Define platforms to be set up
PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.CLIMATE]


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the Alsavo Pro component."""
    # This function is largely unused in modern integrations but required.
    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up the Alsavo Pro heater from a config entry."""
    name = entry.data.get(CONF_NAME)
    serial_no = entry.data.get(SERIAL_NO)
    ip_address = entry.data.get(CONF_IP_ADDRESS)
    port_no = entry.data.get(CONF_PORT)
    password = entry.data.get(CONF_PASSWORD)

    data_handler = AlsavoPro(name, serial_no, ip_address, port_no, password)
    # The first update is done within the coordinator's first refresh
    data_coordinator = AlsavoProDataCoordinator(hass, data_handler)

    # Perform the first refresh to catch any connection issues early
    await data_coordinator.async_config_entry_first_refresh()

    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = data_coordinator

    # --- CHANGED SECTION ---
    # The old `async_forward_entry_setup` is deprecated.
    # The new `async_forward_entry_setups` (plural) handles all platforms at once.
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    # --- END CHANGED SECTION ---

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    # --- CHANGED SECTION ---
    # The old `async_forward_entry_unload` is also deprecated.
    # The new `async_forward_entry_unloads` (plural) unloads all platforms at once.
    # It returns True if all platforms were unloaded successfully.
    return await hass.config_entries.async_forward_entry_unloads(entry, PLATFORMS)
    # --- END CHANGED SECTION ---


class AlsavoProDataCoordinator(DataUpdateCoordinator):
    """Class to manage fetching Alsavo Pro data from the device."""

    def __init__(self, hass: HomeAssistant, data_handler: AlsavoPro):
        """Initialize my coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="AlsavoPro",
            update_interval=timedelta(seconds=15),
        )
        self.data_handler = data_handler

    async def _async_update_data(self):
        """Fetch data from API endpoint.

        This is the place to pre-process the data to lookup tables
        so entities can quickly look up their data.
        """
        _LOGGER.debug("Starting data update from Alsavo Pro device")
        try:
            # Note: The timeout is handled by the coordinator.
            async with async_timeout.timeout(10):
                await self.data_handler.update()
                _LOGGER.debug("Data update successful")
                return self.data_handler
        except Exception as ex:
            # The coordinator will automatically log the exception and handle retries.
            _LOGGER.error("Error communicating with Alsavo Pro device: %s", ex)
            # Re-raise the exception to be caught by the DataUpdateCoordinator
            raise
```

**Comment by lesotter** [comment]
..and did you overwite the /config/custom_components/alsavopro/init.py rather than what looks like File "/usr/local/lib/python3.13/importlib/init.py" in your case?

**Comment by lesotter** [comment]
please ensure the "r" in raise is directly below the "_" of "_LOGGER" above it.  Any indentation error here would cause your syntax error on raise keyword

**Comment by dgillet1380** [comment]
I tried Google AI... no joy.

**Comment by lesotter** [comment]
did you re-copy and paste my code above?

**Comment by dgillet1380** [comment]
Yes, it didn't work.
However, using Google AI, it worked on the third iteration, after feeding Goggle with the HA generated error messages!
Thanks for the tip!
Denis

**Comment by dgillet1380** [comment]
Here is the code:
----------------------------------------------------------

"""Alsavo Pro pool heat pump integration."""
import logging
from datetime import timedelta

import async_timeout

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    CONF_IP_ADDRESS,
    CONF_NAME,
    CONF_PASSWORD,
    CONF_PORT,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .AlsavoPyCtrl import AlsavoPro
from .const import DOMAIN, SERIAL_NO

_LOGGER = logging.getLogger(__name__)

# Define the platforms that this integration will support.
PLATFORMS: list[str] = ["climate", "sensor"]


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up the Alsavo Pro heater from a config entry."""
    # Extract configuration from the config entry.
    ip_address = entry.data[CONF_IP_ADDRESS]
    password = entry.data[CONF_PASSWORD]
    port_no = entry.data[CONF_PORT]
    serial_no = entry.data[SERIAL_NO]
    name = entry.data[CONF_NAME]

    # Create the data handler and coordinator.
    data_handler = AlsavoPro(name, serial_no, ip_address, port_no, password)
    coordinator = AlsavoProDataCoordinator(hass, data_handler)

    # Fetch initial data so we have everything before setting up platforms.
    await coordinator.async_config_entry_first_refresh()

    # Store the coordinator in hass.data for platforms to access.
    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = coordinator

    # Forward the setup to the supported platforms.
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    # Unload the platforms using the new helper.
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


class AlsavoProDataCoordinator(DataUpdateCoordinator):
    """Manages fetching and coordinating data for the Alsavo Pro integration."""

    def __init__(self, hass: HomeAssistant, data_handler: AlsavoPro) -> None:
        """Initialize the data coordinator."""
        super().__init__(
            hass,
            _LOGGER,
            name="AlsavoPro",
            update_interval=timedelta(seconds=15),
        )
        self.data_handler = data_handler

    async def _async_update_data(self) -> AlsavoPro:
        """Fetch data from the Alsavo Pro device."""
        try:
            # Use a timeout to prevent the integration from hanging.
            async with async_timeout.timeout(10):
                await self.data_handler.update()
                return self.data_handler
        except Exception as ex:
            # Raise a specific exception to notify Home Assistant of the failure.
            raise UpdateFailed(f"Error communicating with API: {ex}") from ex

**Comment by goev** [comment]
Sorry for the delay! This should be fixed now.
